/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    categories: Category;
    products: Product;
    cultures: Culture;
    solutions: Solution;
    distributors: Distributor;
    'blog-categories': BlogCategory;
    posts: Post;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    cultures: CulturesSelect<false> | CulturesSelect<true>;
    solutions: SolutionsSelect<false> | SolutionsSelect<true>;
    distributors: DistributorsSelect<false> | DistributorsSelect<true>;
    'blog-categories': BlogCategoriesSelect<false> | BlogCategoriesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    home: Home;
    settings: Setting;
  };
  globalsSelect: {
    home: HomeSelect<false> | HomeSelect<true>;
    settings: SettingsSelect<false> | SettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  name: string;
  /**
   * Адреса фільтра: /preparaty?cat=<слаг>
   */
  slug: string;
  description?: string | null;
  /**
   * Менше число — вище в списку
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  name: string;
  /**
   * Для вузьких місць: картки, хлібні крихти
   */
  shortName?: string | null;
  category: number | Category;
  tagline?: string | null;
  description: string;
  image?: (number | null) | Media;
  /**
   * Наприклад: 10 кг, 5 л
   */
  packaging?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  intro?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  keySpecs?:
    | {
        label: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  specs?:
    | {
        title: string;
        body?:
          | {
              text: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  advantages?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  usage?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  mixing?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  compatibility?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  storage?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  /**
   * З цих рядків будуються сторінки культур. Назву культури пишіть однаково у всіх препаратах — інакше зʼявиться дубль-сторінка.
   */
  regulations?:
    | {
        culture: string;
        rate: string;
        id?: string | null;
      }[]
    | null;
  problems?:
    | {
        title: string;
        body?:
          | {
              text: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Найдешевший спосіб потрапити у відповіді ChatGPT, Perplexity і Google AI. Питання формулюйте так, як їх ставить агроном («Яка норма на кукурудзу?»), а не як написано на етикетці. Відповідь — 2-4 речення, конкретно. Оптимально 4-6 питань; блок зʼявляється на сторінці препарату, коли є хоча б одне.
   */
  faq?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Те, що видно синім рядком у Google. Google обрізає все після ~60 символів. Порожнє поле — заголовок збереться з назви препарату.
   */
  seoTitle?: string | null;
  /**
   * Сірий текст під заголовком у видачі. На позиції не впливає, на клікабельність — прямо. Коротше 120 символів — половина місця марно, довше 165 — обріжеться.
   */
  metaDescription?: string | null;
  /**
   * Адреса сторінки: /preparaty/<слаг>
   */
  slug: string;
  featured?: boolean | null;
  /**
   * Менше число — вище в списку
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cultures".
 */
export interface Culture {
  id: number;
  name: string;
  /**
   * Адреса сторінки: /kultury/<слаг>
   */
  slug: string;
  intro?: string | null;
  /**
   * Ці рядки показуються на сторінці культури і вмикають культуру у фільтрі каталогу.
   */
  products?:
    | {
        product: number | Product;
        /**
         * Порожньо — покажемо «норма уточнюється у консультанта»
         */
        rate?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Менше число — вище в списку
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "solutions".
 */
export interface Solution {
  id: number;
  title: string;
  /**
   * Адреса сторінки: /rishennia/<слаг>
   */
  slug: string;
  lead: string;
  paragraphs?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  products?: (number | Product)[] | null;
  /**
   * Менше число — вище в списку
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "distributors".
 */
export interface Distributor {
  id: number;
  name: string;
  logo?: (number | null) | Media;
  /**
   * Фільтр на сторінці дистрибʼюторів: Садівництво, Овочівництво, Технічні культури…
   */
  direction: string;
  role?: string | null;
  phones?:
    | {
        number: string;
        id?: string | null;
      }[]
    | null;
  address?: string | null;
  /**
   * Менше число — вище в списку
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-categories".
 */
export interface BlogCategory {
  id: number;
  name: string;
  /**
   * Адреса: /blog/category/<слаг>
   */
  slug: string;
  description?: string | null;
  /**
   * Менше число — вище в списку
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  /**
   * Адреса статті: /blog/<слаг>
   */
  slug: string;
  excerpt: string;
  category: number | BlogCategory;
  cover?: (number | null) | Media;
  /**
   * Заповніть — і Google зможе показати статтю розширеним сніпетом із датою. Порожнє поле краще за вигадану дату: дата в розмітці — це заявлений факт.
   */
  date?: string | null;
  /**
   * Прізвище агронома чи фахівця, якщо матеріал авторський. Порожнє — автором вважається компанія. Авторство — прямий сигнал E-E-A-T для Google і для AI-пошуку.
   */
  author?: string | null;
  /**
   * Заголовки статей довгі, а Google показує ~60 символів і решту зрізає. Порожнє — заголовок обріжеться автоматично по слову.
   */
  seoTitle?: string | null;
  /**
   * Порожнє — візьметься короткий опис вище, обрізаний по слову.
   */
  metaDescription?: string | null;
  /**
   * Лишіть порожнім — порахується з обсягу тексту
   */
  readMinutes?: number | null;
  tags?:
    | {
        label: string;
        slug: string;
        kind: 'product' | 'culture';
        id?: string | null;
      }[]
    | null;
  /**
   * Блоки йдуть у тому порядку, у якому стоять тут
   */
  blocks?:
    | {
        kind: 'paragraph' | 'heading' | 'list';
        text?: string | null;
        items?:
          | {
              text: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  published?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'cultures';
        value: number | Culture;
      } | null)
    | ({
        relationTo: 'solutions';
        value: number | Solution;
      } | null)
    | ({
        relationTo: 'distributors';
        value: number | Distributor;
      } | null)
    | ({
        relationTo: 'blog-categories';
        value: number | BlogCategory;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  name?: T;
  shortName?: T;
  category?: T;
  tagline?: T;
  description?: T;
  image?: T;
  packaging?:
    | T
    | {
        text?: T;
        id?: T;
      };
  intro?:
    | T
    | {
        text?: T;
        id?: T;
      };
  keySpecs?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  specs?:
    | T
    | {
        title?: T;
        body?:
          | T
          | {
              text?: T;
              id?: T;
            };
        id?: T;
      };
  advantages?:
    | T
    | {
        text?: T;
        id?: T;
      };
  usage?:
    | T
    | {
        text?: T;
        id?: T;
      };
  mixing?:
    | T
    | {
        text?: T;
        id?: T;
      };
  compatibility?:
    | T
    | {
        text?: T;
        id?: T;
      };
  storage?:
    | T
    | {
        text?: T;
        id?: T;
      };
  regulations?:
    | T
    | {
        culture?: T;
        rate?: T;
        id?: T;
      };
  problems?:
    | T
    | {
        title?: T;
        body?:
          | T
          | {
              text?: T;
              id?: T;
            };
        id?: T;
      };
  faq?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  seoTitle?: T;
  metaDescription?: T;
  slug?: T;
  featured?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cultures_select".
 */
export interface CulturesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  intro?: T;
  products?:
    | T
    | {
        product?: T;
        rate?: T;
        id?: T;
      };
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "solutions_select".
 */
export interface SolutionsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  lead?: T;
  paragraphs?:
    | T
    | {
        text?: T;
        id?: T;
      };
  products?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "distributors_select".
 */
export interface DistributorsSelect<T extends boolean = true> {
  name?: T;
  logo?: T;
  direction?: T;
  role?: T;
  phones?:
    | T
    | {
        number?: T;
        id?: T;
      };
  address?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-categories_select".
 */
export interface BlogCategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  category?: T;
  cover?: T;
  date?: T;
  author?: T;
  seoTitle?: T;
  metaDescription?: T;
  readMinutes?: T;
  tags?:
    | T
    | {
        label?: T;
        slug?: T;
        kind?: T;
        id?: T;
      };
  blocks?:
    | T
    | {
        kind?: T;
        text?: T;
        items?:
          | T
          | {
              text?: T;
              id?: T;
            };
        id?: T;
      };
  published?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home".
 */
export interface Home {
  id: number;
  eyebrow?: string | null;
  /**
   * Перша частина заголовка, темним
   */
  titleBefore?: string | null;
  /**
   * Слово, яке підсвічується салатовим
   */
  titleAccent?: string | null;
  subtitle?: string | null;
  /**
   * Широке фото, від 1920px. Порожньо — лишиться поточне.
   */
  background?: (number | null) | Media;
  stats?:
    | {
        value: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  primaryCta?: string | null;
  secondaryCta?: string | null;
  aboutEyebrow?: string | null;
  aboutTitle?: string | null;
  aboutText?: string | null;
  aboutLink?: string | null;
  /**
   * Ілюстрація підбирається за типом картки
   */
  trust?:
    | {
        title: string;
        text: string;
        icon: 'certificate' | 'organic' | 'micron' | 'safe';
        id?: string | null;
      }[]
    | null;
  ctaEyebrow?: string | null;
  ctaTitle?: string | null;
  ctaSubtitle?: string | null;
  ctaSubmit?: string | null;
  ctaLegal?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings".
 */
export interface Setting {
  id: number;
  company?: string | null;
  /**
   * Показуються в шапці, бургер-меню і CTA-блоках. Три цілком достатньо.
   */
  phones?:
    | {
        label: string;
        value: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  allPhones?:
    | {
        group: string;
        numbers?:
          | {
              number: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  email?: string | null;
  address?: string | null;
  socials?:
    | {
        name: 'facebook' | 'instagram' | 'youtube' | 'tiktok';
        href: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Більше семи пунктів у шапку не влазить — восьмий переносить меню на другий рядок.
   */
  nav?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  footerColumns?:
    | {
        title: string;
        links?:
          | {
              label: string;
              href: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  legalName?: string | null;
  edrpou?: string | null;
  legalAddress?: string | null;
  postalAddress?: string | null;
  /**
   * Показується на /privacy і /terms
   */
  legalUpdated?: string | null;
  delivery?:
    | {
        title: string;
        note?: string | null;
        icon?: ('truck' | 'pin') | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home_select".
 */
export interface HomeSelect<T extends boolean = true> {
  eyebrow?: T;
  titleBefore?: T;
  titleAccent?: T;
  subtitle?: T;
  background?: T;
  stats?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  primaryCta?: T;
  secondaryCta?: T;
  aboutEyebrow?: T;
  aboutTitle?: T;
  aboutText?: T;
  aboutLink?: T;
  trust?:
    | T
    | {
        title?: T;
        text?: T;
        icon?: T;
        id?: T;
      };
  ctaEyebrow?: T;
  ctaTitle?: T;
  ctaSubtitle?: T;
  ctaSubmit?: T;
  ctaLegal?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings_select".
 */
export interface SettingsSelect<T extends boolean = true> {
  company?: T;
  phones?:
    | T
    | {
        label?: T;
        value?: T;
        href?: T;
        id?: T;
      };
  allPhones?:
    | T
    | {
        group?: T;
        numbers?:
          | T
          | {
              number?: T;
              id?: T;
            };
        id?: T;
      };
  email?: T;
  address?: T;
  socials?:
    | T
    | {
        name?: T;
        href?: T;
        id?: T;
      };
  nav?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  footerColumns?:
    | T
    | {
        title?: T;
        links?:
          | T
          | {
              label?: T;
              href?: T;
              id?: T;
            };
        id?: T;
      };
  legalName?: T;
  edrpou?: T;
  legalAddress?: T;
  postalAddress?: T;
  legalUpdated?: T;
  delivery?:
    | T
    | {
        title?: T;
        note?: T;
        icon?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}